FROM almalinux:9
ENV COURSE="DevOps" \
    TRAINER="Sivakumar" \
    DURATION="120HRS"
CMD ["sleep","1000"]
## sleep for 1000 seconds, container is running mode while it was in sleep mode
## we need to give CMD instruction to keep the container in active mode
## either it is sleep or some other activity